version: "3.3"

services:
  web:
    build: .
    container_name: Damn-Vulnerable-LMS-App
    ports:
      - "5050:5000"
    volumes:
      - .:/app                
      - ./database.db:/app/database.db  
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    restart: unless-stopped
